[package]
name = "rustapp"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustapp"
crate-type = ["staticlib"]

[dependencies]
cortex-m = "0.7"
xwrust = {path = "../../../../xwmd/xwrust"}
libc-print = "0.1"
