[package]
name = "xwos"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "xwos"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"
newlib-alloc = "0.1"
libc-print = "0.1"