[package]
name = "xwrust"
version = "1.0.0"
edition = "2021"
authors = ["Roy Sun <xwos@xwos.tech>"]
description = "XWOS Rust Framework"
license = "MPL-2.0"

[lib]
name = "xwrust"

[dependencies]
libc = "0.2"
cstr_core = "0.2"
cty = "0.2"