[package]
name = "xwrust_example_cond"
version = "0.1.0"
edition = "2021"
authors = ["Roy Sun <xwos@xwos.tech>"]
description = "XWOS RUST Condition Example"
license = "Apache-2.0"

[lib]
name = "xwrust_example_cond"

[dependencies]
xwrust = {path = "../../../xwmd/xwrust"}
libc-print = "0.1"