[package]
name = "rustbtn"
version = "0.1.0"
edition = "2021"
authors = ["Roy Sun <xwos@xwos.tech>"]
description = "STM32 RUST Button Example"
license = "Apache-2.0"

[lib]
name = "rustbtn"

[dependencies]
xwrust = {path = "../../../../xwmd/xwrust"}
libc-print = "0.1"