#! /bin/bash
# @file
# @brief 生成compile_commands.json的脚本
# @author
# + 隐星曜 (Roy Sun) <xwos@xwos.tech>
# @copyright
# + Copyright © 2015 xwos.tech, All Rights Reserved.
# > Licensed under the Apache License, Version 2.0 (the "License");
# > you may not use this file except in compliance with the License.
# > You may obtain a copy of the License at
# >
# >         http://www.apache.org/licenses/LICENSE-2.0
# >
# > Unless required by applicable law or agreed to in writing, software
# > distributed under the License is distributed on an "AS IS" BASIS,
# > WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# > See the License for the specific language governing permissions and
# > limitations under the License.
#

set -e

script=${0}
script_basename=$(basename ${script})
script_dirname=$(dirname ${script})

######## ######## ######## ######## ######## ######## ########
######## ########           errno            ######## ########
######## ######## ######## ######## ######## ######## ########
EINVAL=22               # Invalid argument

######## ######## ######## ######## ######## ######## ########
######## ########          function          ######## ########
######## ######## ######## ######## ######## ######## ########
function logd()
{
  if [[ "x$CONFIG_DEBUG" = "x1" ]] ; then
    echo -e "\e[1m\e[49;37m[DBG] $1\e[0m"
  fi
}

function loge()
{
  echo -e "\e[1m\e[49;31m[ERR] $1\e[0m"
}

function logw()
{
  echo -e "\e[1m\e[49;33m[WRN] $1\e[0m"
}

function logn()
{
  echo -e "\e[1m\e[46;34m[NOTICE] $1\e[0m"
}

function logi()
{
  echo -e "\e[1m\e[44;37m[INF] $1\e[0m"
}

function vrun()
{
  echo -e "\e[1m\e[44;38m$*\e[0m"
  eval $*
  return $?
}

function usage()
{
  cat <<USAGE_EOF
[Usage]
${script_basename} [-r topdir] [-b builddir] [name]
生成compile_commands.json。
<option>
  -t|--top topdir
    设置工程根目录
  -b|--build builddir
    设置编译目录，相对于rootdir
  -h, --help
    打印本信息
  [name]
    设置输出文件名
USAGE_EOF
}

function is_subpath()
{
    local A="$1"
    local B="$2"
    local rel=$(realpath --relative-to="$A" "$B" 2>/dev/null)

    [ $? -ne 0 ] && return 1
    case "$rel" in
        "" | "." ) return 0 ;;
        ".." | "../"* ) return 1 ;;
        * ) return 0 ;;
    esac
}

######## ######## ######## ######## ######## ######## ########
######## ########        main sctrip         ######## ########
######## ######## ######## ######## ######## ######## ########
## 0. env & argument
topdir=$(cd ${script_dirname}; pwd)
arglist=$(getopt -o ht:b: \
                 --long help,top:,build: \
                 -n "${script_basename}" -- "$@")

if [[ $? != 0 ]] ; then
  loge "getopt error"
  exit $EINVAL
fi

eval set -- "$arglist"

topdir=
builddir=
out=

while true ; do
  case "$1" in
    -t|--top)
      topdir=$2
      shift 2
      ;;
    -b|--build)
      builddir=$2
      shift 2
      ;;
    --)
      out=$2
      break
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      loge "Internal error!"
      usage
      exit $EINVAL
      ;;
  esac
done

if [ x"${topdir}" = x ] ; then
  loge "\${topdir} is empty!"
  usage
  exit $EINVAL
fi

cd ${topdir}
topdir=$(pwd)
logi "topdir: ${topdir}"

if [ x"${builddir}" = x ] ; then
  loge "\${builddir} is empty!"
  usage
  exit $EINVAL
fi

logi "builddir: ${builddir}"

if ! is_subpath "${topdir}" "${builddir}" ; then
  loge "builddir is not the subpath of topdir!"
  exit $EINVAL
fi

cd ${builddir}
vrun rm -f compile_commands.json
vrun make d
vrun bear -- make
sed -i "s|${XWTC}|\${env:XWTC}|g" compile_commands.json
sed -i "s|${topdir}|\${workspaceFolder}|g" compile_commands.json

if [ x"${out}" != x ] ; then
  vrun rm -f ${out}
  vrun mv compile_commands.json ${out}
fi

exit 0
