/* Don't edit this file, because it is generated by xwbs/mkcfg.el */

#ifndef __cfg_autogen_h__
#define __cfg_autogen_h__

#define XWOS_CFG_ARCH__arm 1
#define XWOS_CFG_SUBARCH__v7m 1
#define XWOS_CFG_COMPILER__gcc 1
#define XWOS_CFG_CPU__m7 1
#define XWOS_CFG_SOC__stm32 1
#define XWOS_CFG_BOARD__WeActMiniStm32H750 1
#define XWOS_CFG_CORE__mp 1

#endif /* cfg/autogen.h */
