/* Don't edit this file, because it is generated by xwbs/mkcfg.el */

#ifndef __cfg_autogen_h__
#define __cfg_autogen_h__

#define XWCFG_ARCH__arm 1
#define XWCFG_SUBARCH__v7m 1
#define XWCFG_COMPILER__gcc 1
#define XWCFG_LIBC__newlib 1
#define XWCFG_CPU__m7 1
#define XWCFG_SOC__stm32 1
#define XWCFG_BOARD__WeActMiniStm32H750 1
#define XWCFG_CORE__mp 1

#endif /* cfg/autogen.h */
